### ISSUE TITLE
Unresponsive drop in/drop out button

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#12]
The mechanic works, but sometimes the button needs to be pressed more than once to register.

**Comment by UngratefulFool** [comment]
Completed, added a timer to keep the button from activating multiple times when it was pressed.

**Comment by UngratefulFool** [comment]
Create second timer for second player drop-in/out.

**Comment by UngratefulFool** [comment]
Completed
