### ISSUE TITLE
Allow combat to work with different enemies

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#124]
For now, it would be good to have it so that both the baby-piano abomination and troll placeholders can be fought, and have a functioning combat scene with both. We need to be able to have different traits, hit boxes, AIs, etc on each.

**Comment by UngratefulFool** [comment]
The way I envision it is that each player/enemy will have the same basic properties. We can change the nodes just by instancing. But could you talk a little more about what specific things you want some enemies to have that would be different from what we currently have? I would like to determine if we should make combatEnemy be an abstract class that we just use for each enemy, or if we just contain everything in combatEnemy and then load information into it to specify the fighting parameters.

**Comment by cbcerquiaga** [comment]
I think the biggest differences will be the collision box for different sprites, their stats, and running different AI scripts. I think an abstract class would be the easier way to do it, but however you think is best is fine with me

**Comment by UngratefulFool** [comment]
Todo: Instance another enemy so that we can test the concept

**Comment by UngratefulFool** [comment]
Completed, if there are any additional parameters you want me to include with the players let me know. I can test out anything by overloading the methods.
