### ISSUE TITLE
UI is not centered properly with the screen

### ISSUE THREAD

**Issue by UngratefulFool** [cbcerquiaga/YouMeAndTheEndOfTheWorld#125]
The camera is created by adjusting the viewport. When setting the location of the screen we have not been able to follow the location of the viewport. We want the UI to appear in certain places in relation to the current viewport.

The way I see it we have two approaches to tackling this problem:
1. We adjust how the camera moves with the players to see if we can use the built in code to handle the UI placement.
2. We try to adjust the UI to take into the account the viewport transforms. This could either mean tracking the changes to the viewport as determined in update_camera() in SceneManager.gd. Or we need to get the viewport, and then use it to determine the location we need to place the UI, so far this has not provided fruitful, but we could be doing it wrong.

**Comment by cbcerquiaga** [comment]
I think 2 is the better option. The issue is turning a Transform2D object into a Vector2 so it can be applied to the UI elements

**Comment by cbcerquiaga** [comment]
Duplicat eof #108
