### ISSUE TITLE
Inventory screen shows duplicates

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#134]
After adding multiple pianos, the inventory shows 2 separate pianos. Should the items be stored as a dictionary (with the key keeping their quantity) rather than as an array? @UngratefulFool

**Comment by UngratefulFool** [comment]
This is one of the two ways of handling it, the issue with that is then when we have 5 coins on the ground that needs to be stored as an item. And that item is different from 10 coins.
