### ISSUE TITLE
Players can delete each other

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#14]
The collision handler for doors deletes the players if they run into each other

**Comment by UngratefulFool** [comment]
This is not an issue on my repo, what did you change? The only way the collision could affect the player is if they have a collision handler method, the door method only removes self, troll is not pass into the method, so troll couldn't be removed.

**Comment by UngratefulFool** [comment]
I pulled the changes and the issue appears to be that the second player's script was set to the door script. This is incorrect. I changed it back to player2's script and the issue is resolved.
