### ISSUE TITLE
Players colliding with walls are slowed

### ISSUE THREAD

**Issue by UngratefulFool** [cbcerquiaga/YouMeAndTheEndOfTheWorld#15]
When the player is colliding with a wall, they are very slow. There should be a way for them to move a little more smoothly across the walls.

**Comment by cbcerquiaga** [comment]
Even with the adjusted collision boxes, this is still a problem

**Comment by UngratefulFool** [comment]
I was saying we could adjust the collision box if the player couldn’t move through a doorway, this has to do with the _move_and_collide() method the players are using now

**Comment by UngratefulFool** [comment]
Completed, I switched back to move_and_slide() method. The move_and_collide() method stops the player once they collide. At first I thought move_and_collide() was the only method that would give us collision objects, but this is not true. move_and_slide() gives us a list of collision objects, so I just have to parse through several objects after each move.
