### ISSUE TITLE
Let players advance into another area

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#19]
If a player advances over the edge of the current map area, they should be given a choice as to whether or not they want to go to the next area and what time it will be when they arrive, then the game should pause. Later, we can add a screen for managing both players' health from a collective inventory (we can decide how we want to do that later) but for now just a plain pop-up with a "click to continue" will do. We should also add skeleton code for how to implement chance encounters when this happens- for now we can just have it such that we generate a random number and print it.

**Comment by UngratefulFool** [comment]
We can add a special block, similar to a goal or a master door that when they collide or interact with it they will start a new stage. Stages will have to be changed, we are currently using dungeon.tscn as the current stage, perhaps we just change that and pass in the variables of the player after they complete each stage or move from 1 to another.

**Comment by UngratefulFool** [comment]
Completed, I just added a different door object with the same sprite, you can see this on the North west part of the wall.
