### ISSUE TITLE
Implement perks for player characters

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#21]
I imagine something like a Set or a Dictionary of strings, though I don't know how we would actually apply perk benefits

**Comment by UngratefulFool** [comment]
Is there a list of perks that I can look at? Being able to see what we want to add (double damage, flying, infinite storage space, etc) because then I can try to think about the best way of storing the perks.

**Comment by cbcerquiaga** [comment]
You're in...not luck! That list is undecided, but the good news is that nothing will be game-breaking like being able to fly. I'll put up a brainstorming file so we can come up with some together.

**Comment by UngratefulFool** [comment]
Completed, I added basic perks to the playerProperties. speedBonus was the only one I could reasonably add to show how it will work.
