### ISSUE TITLE
Add a HUD

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#24]
What would be most important to the HUD, and what should it look like?

**Comment by UngratefulFool** [comment]
Showing what items they have selected, if they have a hotbar of items, health, xp

**Comment by cbcerquiaga** [comment]
![hud mockup](https://user-images.githubusercontent.com/21173989/41100192-b4758438-6a2e-11e8-912c-fb677103cb8c.png)

**Comment by cbcerquiaga** [comment]
That's a mockup for what I was thinking. The big circle would have a player portrait, which we could change to a status symbol if the player is starving to death or some other big problem. Red would be general health (we'd need to come up with a formula for it), blue EXP, green carry capacity available (so they don't need to look at their inventory to see how full it is).
The big squares would show a symbol for an action that is available for that action button, and next to the little circles would be text for what the player has hotkeyed (and if they haven't hotkeyed anything, we would have 0 circles there).

Obviously this is a rough sketch, but do you guys think this would be good?

**Comment by cbcerquiaga** [comment]
I've added the skeletons and the nodes for the progress bars, and polished that initial design a little bit.
