### ISSUE TITLE
Camera unit tests

### ISSUE THREAD

**Issue by dzwiener** [cbcerquiaga/YouMeAndTheEndOfTheWorld#36]
Check that the camera is behaving properly via unit tests. We can check the location of the camera based on where we want it compared to where it currently is. IE, if we move the player right 10 pixels and left 10 pixels the camera should be in it's original location.

**Comment by dzwiener** [comment]
This doesn't seem like it needs to be added.

**Comment by cbcerquiaga** [comment]
I guess it depends on how much you like unit testing
