### ISSUE TITLE
Players shifted when picking up items

### ISSUE THREAD

**Issue by UngratefulFool** [cbcerquiaga/YouMeAndTheEndOfTheWorld#38]
When a player activates their action button they change their collision mask for a tick, then detect any items that were standing on. So far the only way I can detect items is move_and_slide(Vector2(0,0)) or move_and_collide(Vector2(0,0)) and both of these shift the player to the nearest "safe spot".

**Comment by cbcerquiaga** [comment]
What if we made everything absolutely gigantic and zoomed the camera way out (so that way everything is both proportional and looks the same)? Then when it corrects position, it wouldn't be moving as obviously

**Comment by UngratefulFool** [comment]
That is a work around, I am sure there is a way to do it. I wouldn't want to make sacrifices this early in the game development process.

**Comment by UngratefulFool** [comment]
Fixed, I used ray casting instead of the builtin functions of kinematicBody2D.
