### ISSUE TITLE
Make it so the players can open doors

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#5]

**Comment by UngratefulFool** [comment]
http://docs.godotengine.org/en/3.0/tutorials/physics/using_kinematic_body_2d.html#movement-and-collision

**Comment by UngratefulFool** [comment]
Players can now open doors, every object that has a handle_collide() method will be executed when the player touches them. So if there is a treasure chest, or door, or spikes, etc. This method for those objects can interact with the player.
