### ISSUE TITLE
Add ranged v ranged combat to minigame scene

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#50]

**Comment by cbcerquiaga** [comment]
This involves choosing the right spite (and frame) for both the player's and enemy's ammo counters depending on their current weapon, changing the mouse cursor to an aiming reticle, making it so that the player shoots towards the mouse on a click, making projectiles that hit the enemy do damage, and making the ammo counter go down each time shots are fired.

**Comment by UngratefulFool** [comment]
Would this issue be considered completed? I know combat is done, but both players have counters and the player is able to shoot, perhaps we just need to add the ability for the enemy to shoot the player to consider this to be done?

**Comment by cbcerquiaga** [comment]
Yes, I think it's completed. I'll add a few more issues for fleshing it out and balancing it.
