### ISSUE TITLE
PlayerProperties unit tests

### ISSUE THREAD

**Issue by dzwiener** [cbcerquiaga/YouMeAndTheEndOfTheWorld#52]
Create unit tests to test PlayerProperties.gd.

**Comment by UngratefulFool** [comment]
Currently the only interesting thing about playerProperties is that it has a fully functioning Inventory, but that is stored in Inventory.gd. We already test Inventory.gd pretty well, so the rest of playerProperties testing will have to be with stats, traits and perks. But the effects of these unimplemented features is not testable yet.
