### ISSUE TITLE
Let the player damage the enemy

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#68]
Either by clicking (shooting) or with melee attacks

**Comment by cbcerquiaga** [comment]
We could do this in the enemy script or in the bullet script, but it makes more sense in the enemy script, right? What do you think, @UngratefulFool?

**Comment by UngratefulFool** [comment]
Enemy script, we can signal every hit and then have the player detect signals and respond accordingly.

**Comment by UngratefulFool** [comment]
Completed, I didn't do signals because we are creating instances of the bullets, so the signals cannot be created on the fly to my knowledge. So I just loaded the enemy node to the bullet and called the function when it contacts. This is functional, not optimal.

**Comment by UngratefulFool** [comment]
Completed using signals, still needs to know the enemy node, but perhaps this will be a little easier in the future.
