### ISSUE TITLE
Make the camera zoom in and out so both players are always on screen

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#7]
At the moment, the camera just follows player 2 and player 1 can get lost offscreen. I think the easiest way to fix this problem is just to have the camera zoom out when the players are too far apart for both of them to be onscreen. We could alternatively split the screen or make it so that players can't move off the screen without both of them going the same way, but I think this approach makes the most sense for how we want the game to be played.

**Comment by UngratefulFool** [comment]
Made it so the camera follows p1 at all times unless p1 drops out, then the main camera switches to p2.

**Comment by UngratefulFool** [comment]
I made the camera follow the two players, it does not yet zoom out. Do we need the camera to follow 1 player when they dropout? If not, I can stop working on that. I assume that the player dropped out will just follow the player, therefore the camera does not need to update to be fixed on 1 player.

**Comment by cbcerquiaga** [comment]
Correct. We need to work on the pathfinding/following still but that's the plan.

**Comment by UngratefulFool** [comment]
Completed, I created constants that can be changed to our liking, such as the margin for when it begins zooming out, the minimum zoom and the maximum zoom.
