### ISSUE TITLE
Add assets for other ammo counters

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#71]
There needs to be a 6 shot revolver, and 8 shot revolver, a musket, an automatic gun, and just a number counter...or maybe just figure out a number counter?

**Comment by UngratefulFool** [comment]
We could display bullets, so if they have a machine gun they might have 32 bullets that will delete as fired.

**Comment by cbcerquiaga** [comment]
Great idea! That way, the player can tell what kind of weapon they and the enemy have, and there's way fewer assets to make (maybe just 2 or bullets, a knife, and an arrowhead)

**Comment by UngratefulFool** [comment]
If we want to get more technical we can make different bullet assets, we just have to find a way to properly organize bullets on the screen. We don't want 180 bullets being displayed the same as 4 bullets.
