### ISSUE TITLE
Make hovering the mouse over an item display info text

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#78]
In the exploring scene, hovering the mouse cursor over an item, person, or sign should reveal text about it- either the name of the item/person, or what a sign says. Maybe clicking should reveal even more text, or make the text stay when the mouse leaves, or highlight the selected thing, or mark the map?

**Comment by UngratefulFool** [comment]
Completed this with just one item, I can implement it for each item, but I should come up with a way to have the abstract class item.gd handle this and pass the itemName into the popup. That shouldn't be hard but the signals mouse_entered and mouse_exited do not allow for parameters being checks. So either I find another way of detecting the cursor colliding with items on the field, or I find another way of detecting mouse_entered and mouse_exited.

**Comment by UngratefulFool** [comment]
Completed, thing to note: pickable off means the mouse entering and exiting will not send out a signal.
