### ISSUE TITLE
Make clicking outside of combat area not waste a shot of ammo

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#86]
It shouldn't cost any bullets to surrender or run away

**Comment by UngratefulFool** [comment]
Completed, I made the whole border not count, see if you like it, if not I can limit it to just the top portion of the screen. I was also thinking the player might click when their mouse is outside the window and that may cause 1 bullet to be shot when they click back in.
